In [5]:
import pandas as pd
import numpy as np

#데이터 시각화
import matplotlib
import matplotlib.pyplot as plt

# Scaling 클래스
from sklearn.preprocessing import scale, minmax_scale,robust_scale
# matplotlib 이용한 Background 그래프 실행 및 결과 확인
%matplotlib inline

In [6]:
df_raw = pd.read_csv("시청률_평균.csv", encoding='cp949')
df_raw.head()

     날짜    시간     시청률
0  1월1일  2:00  0.0007
1  1월1일  2:20  0.0000
2  1월1일  2:40  0.0000
3  1월1일  3:00  0.0000
4  1월1일  3:20  0.0000

In [8]:
# 날짜
date = df_raw["날짜"].str.split("월", n=2, expand=True)
df_raw['월'] = date[0].to_frame()
df_raw['일'] = date[1].to_frame()

date = df_raw["일"].str.split("일", n=1, expand=True)
df_raw['일'] = date[0].to_frame()

df_raw = df_raw.drop(['날짜'], axis=1)

df_raw['월']= df_raw['월'].astype(int)
df_raw['일']= df_raw['일'].astype(int)

# 시간
hour = df_raw["시간"].str.split(":", n=2, expand=True)
df_raw['시'] = hour[0].to_frame()
df_raw['분'] = hour[1].to_frame()

df_raw = df_raw.drop(['시간'], axis=1)

df_raw['시']= df_raw['시'].astype(int)
df_raw['분']= df_raw['분'].astype(int)

df_raw.head()

      시청률  월  일  시   분
0  0.0007  1  1  2   0
1  0.0000  1  1  2  20
2  0.0000  1  1  2  40
3  0.0000  1  1  3   0
4  0.0000  1  1  3  20

In [10]:
df_raw.to_csv('df_time_mean.csv', index=False, encoding='cp949')